In [5]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "name" : ['Alfread', 'batman', "Catwomen"],
    "Toy" : [np.nan, 'Batmobile', 'Bullwhip'],
    "born" : [pd.NaT,np.timedelta64,
              pd.NaT]})

In [22]:
print(df)

       name        Toy       born
0   Alfread        NaN        NaT
1    batman  Batmobile 1940-04-25
2  Catwomen   Bullwhip        NaT

In [25]:
df.dropna( how='all')

       name        Toy       born
0   Alfread        NaN        NaT
1    batman  Batmobile 1940-04-25
2  Catwomen   Bullwhip        NaT

In [26]:
df.dropna()

     name        Toy       born
1  batman  Batmobile 1940-04-25

# Drop Duplicate....

In [30]:
df.drop_duplicates(subset=['name'], keep='last')

       name        Toy       born
0   Alfread        NaN        NaT
1    batman  Batmobile 1940-04-25
2  Catwomen   Bullwhip        NaT

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   Toy     2 non-null      str
 2   born    1 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [32]:
# Unique value
df['name'].values

<StringArray>
['Alfread', 'batman', 'Catwomen']
Length: 3, dtype: str

In [34]:
df['Toy'].value_counts(dropna=False)

Toy
NaN          1
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [35]:
df.isnull()

    name    Toy   born
0  False   True   True
1  False  False  False
2  False  False   True

In [36]:
df.describe()

                      born
count                    1
mean   1940-04-25 00:00:00
min    1940-04-25 00:00:00
25%    1940-04-25 00:00:00
50%    1940-04-25 00:00:00
75%    1940-04-25 00:00:00
max    1940-04-25 00:00:00

In [37]:
df.max()

name                 batman
Toy                Bullwhip
born    1940-04-25 00:00:00
dtype: object

In [38]:
df.value_counts()

name    Toy        born
batman  Batmobile  1940-04-25    1
Name: count, dtype: int64